const PORT = process.env.PORT;
const NODE_ENV = process.env.NODE_ENV;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const GOOGLE_CALENDAR_CREDENTIALS = process.env.GOOGLE_CALENDAR_CREDENTIALS;
const MONGODB_URL = process.env.MONGODB_URL;
const MAILTRAP_USER = process.env.MAILTRAP_USER;
const MAILTRAP_PASSWORD = process.env.MAILTRAP_PASSWORD;
const MAIL_TRAP_API_KEY = process.env.MAIL_TRAP_API_KEY;
const MAIL_TRAP_SANDBOX_API_KEY = process.env.MAIL_TRAP_SANDBOX_API_KEY;
const MAIL_TRAP_SMTP_PASS = process.env.MAIL_TRAP_SMTP_PASS;
const MAIL_TRAP_SMTP_USER = process.env.MAIL_TRAP_SMTP_USER;
const DEFAULT_FROM_EMAIL = process.env.DEFAULT_FROM_EMAIL;
const TIMEZONE = process.env.TIMEZONE;
const LOG_LEVEL = process.env.LOG_LEVEL;

module.exports = {
	PORT,
	NODE_ENV,
	GEMINI_API_KEY,
	GOOGLE_CALENDAR_CREDENTIALS,
	MONGODB_URL,
	MAILTRAP_USER,
	MAILTRAP_PASSWORD,
	MAIL_TRAP_API_KEY,
	MAIL_TRAP_SANDBOX_API_KEY,
	MAIL_TRAP_SMTP_PASS,
	MAIL_TRAP_SMTP_USER,
	DEFAULT_FROM_EMAIL,
	TIMEZONE,
	LOG_LEVEL
};
